`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 2026/06/26 15:42:39
// Design Name: 
// Module Name: top
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: AD7606/AD7606C parallel read controller.
//
//              rst_n (active low) from PS FCLK_RESET0_N resets all state and
//              clears error flags. The ADC itself is reset by the S_RESET state,
//              which drives adc_reset high for RESET_CLKS cycles.
//
//              The sampling time base is generated by an independent fixed-period
//              sample_tick generator. CONVST is launched only on sample_tick.
//              The read FSM must finish conversion/readout within one sample
//              period. If it cannot finish, overrun_o is pulsed.
//
//              Channel data is read sequentially via adc_db_synced (registered
//              input bus for metastability protection), copied into temporary
//              registers, moved to a frame buffer when the frame is complete,
//              and transferred to ch1_data~ch4_data on the next sample_tick.
//              Output data_valid aligns to the strict sample period, with one
//              sample-frame latency.
// 
// Dependencies: sample_tick_gen.v
// 
// Revision:
// Revision 0.01 - File Created
// Revision 0.02 - Add temporary channel registers for frame-synchronous output
// Revision 0.03 - Add strict sample tick timing and one-frame-latency output
// Revision 0.04 - Remove external rst_n and use register initial values
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////


module adc_sample4 #(
    parameter integer SYS_CLK_HZ       = 50_000_000,
    parameter integer SAMPLE_RATE_HZ   = 100_000,   // AD7606C 可根据实际手册和时序进一步提高
    parameter integer ADC_TOTAL_CH     = 8,         // AD7606/AD7606C=8, AD7606-6=6, AD7606-4=4
    parameter integer RESET_CLKS       = 10,        // 50MHz 下 10clk = 200ns
    parameter integer CONVST_HIGH_CLKS = 2,         // 50MHz 下 2clk = 40ns
    parameter integer RD_LOW_CLKS      = 5,         // 50MHz 下 5clk = 100ns (满足 t_ACC=31ns + 充分余量)
    parameter integer RD_HIGH_CLKS     = 2          // 50MHz 下 2clk = 40ns
)(
    input  wire        clk,
    input  wire        rst_n,

    // =========================
    // AD7606/AD7606C -> FPGA
    // =========================
    input  wire        adc_busy,
    input  wire [15:0] adc_db,

    // =========================
    // FPGA -> AD7606/AD7606C
    // =========================
    output reg         adc_convst_a = 1'b0,
    output reg         adc_convst_b = 1'b0,
    output reg         adc_cs_n     = 1'b1,
    output reg         adc_rd_n     = 1'b1,
    output reg         adc_reset    = 1'b1,

    output wire [2:0]  adc_os,
    output reg         data_valid = 1'b0,
    output wire signed [63:0] data_out,

    output reg         overrun_o  = 1'b0,
    output reg         underrun_o = 1'b0

);

    // 只保留前四个通道。
    // 这四个输出只在 sample_tick 时同步更新，data_valid 也与 sample_tick 对齐.
    wire        adc_range;
    wire        adc_stby;
    wire        adc_ref_select;
    wire        adc_par_ser_byte_sel;
    (* keep = "true", mark_debug = "true" *) reg signed [15:0] ch1_data;
    (* keep = "true", mark_debug = "true" *) reg signed [15:0] ch2_data;
    (* keep = "true", mark_debug = "true" *) reg signed [15:0] ch3_data;
    (* keep = "true", mark_debug = "true" *) reg signed [15:0] ch4_data;
    // (* keep = "true", mark_debug = "true" *) reg               data_valid;

    assign data_out = {ch1_data, ch2_data, ch3_data, ch4_data};


    // ============================================================
    // 固定配置
    // ============================================================

    // 0：并行接口模式
    assign adc_par_ser_byte_sel = 1'b0;

    // 000：关闭过采样
    assign adc_os = 3'b000;

    // 1：±10V 输入范围；0：±5V 输入范围
    assign adc_range = 1'b1;

    // 1：正常工作；STBY=0 时进入 standby 或 shutdown
    assign adc_stby = 1'b1;

    // 1：使用内部参考源
    assign adc_ref_select = 1'b1;

    // ============================================================
    // 独立采样节拍发生器
    // ============================================================
    // sample_tick 是严格采样时间基准，与 ADC 读数状态机解耦。
    // 正常工作时：
    //   sample_tick[k]   : 启动第 k 帧 CONVST，同时输出第 k-1 帧数据
    //   sample_tick[k+1] : 启动第 k+1 帧 CONVST，同时输出第 k 帧数据

    (* mark_debug = "true" *) wire sample_tick;

    sample_tick_gen #(
        .SYS_CLK_HZ    (SYS_CLK_HZ),
        .SAMPLE_RATE_HZ(SAMPLE_RATE_HZ)
    ) u_sample_tick_gen (
        .clk        (clk),
        .sample_tick(sample_tick)
    );

    // ============================================================
    // 状态定义
    // ============================================================

    localparam [3:0]
        S_RESET       = 4'd0,
        S_IDLE        = 4'd1,
        S_CONVST_HIGH = 4'd2,
        S_WAIT_BUSY_H = 4'd3,
        S_WAIT_BUSY_L = 4'd4,
        S_READ_SETUP  = 4'd5,
        S_RD_LOW      = 4'd6,
        S_RD_SAMPLE   = 4'd7,
        S_RD_HIGH     = 4'd8,
        S_DONE        = 4'd9;

    reg [3:0]  state     = S_RESET;
    (* mark_debug = "true" *) reg [3:0]  ch_idx    = 4'd0;
    reg [31:0] delay_cnt = 32'd0;

    // ============================================================
    // 临时通道寄存器
    // ============================================================
    // AD7606/AD7606C 的并行数据是按通道顺序读出的。
    // 这里先把 V1~V4 暂存到 chx_tmp，等所有通道读完后，
    // 再在 S_DONE 状态写入 chx_buf。chx_data 的更新只发生在 sample_tick。

    reg signed [15:0] ch1_tmp = 16'sd0;
    reg signed [15:0] ch2_tmp = 16'sd0;
    reg signed [15:0] ch3_tmp = 16'sd0;
    reg signed [15:0] ch4_tmp = 16'sd0;

    // ============================================================
    // 一帧延迟输出缓冲
    // ============================================================
    // chx_buf 保存已经完整读出的上一帧数据。
    // frame_ready=1 表示 chx_buf 中有一帧完整数据等待在下一个 sample_tick 输出。

    reg signed [15:0] ch1_buf          = 16'sd0;
    reg signed [15:0] ch2_buf          = 16'sd0;
    reg signed [15:0] ch3_buf          = 16'sd0;
    reg signed [15:0] ch4_buf          = 16'sd0;
    reg               frame_ready      = 1'b0;
    reg               sampling_started = 1'b0;

    // 以下两个信号是内部调试标志，不作为顶层端口，避免额外 XDC 约束。
    // 若需要上板观察，可用 ILA 抓取，或后续再改成顶层输出端口。
    (* mark_debug = "true" *) reg sample_overrun  = 1'b0;
    (* mark_debug = "true" *) reg sample_underrun = 1'b0;

    // ============================================================
    // BUSY 同步到 FPGA 时钟域
    // ============================================================

    reg busy_d1 = 1'b0;
    reg busy_d2 = 1'b0;

    always @(posedge clk) begin
        busy_d1 <= adc_busy;
        busy_d2 <= busy_d1;
    end

    wire busy_sync = busy_d2;

    // ============================================================
    // adc_db 输入寄存器 (setup/hold 保护)
    // ============================================================
    // AD7606/AD7606C 的 DB[15:0] 在 RD 拉低后的 t_ACC (max 31ns) 内稳定。
    // 使用两级寄存器流水线，S_RD_SAMPLE 采样第二级，确保数据在 RD 低电平
    // 末尾有充分的建立时间后再被捕获。
    (* mark_debug = "true" *) reg [15:0] adc_db_synced  = 16'd0;
    (* mark_debug = "true" *) reg [15:0] adc_db_synced2 = 16'd0;

    // ila_data ila_data_inst (
    //     .clk(clk),
    //     .probe0(data_valid),
    //     .probe1(ch1_data),
    //     .probe2(ch2_data),
    //     .probe3(ch3_data),
    //     .probe4(ch4_data),
    //     
    //     .probe5(adc_convst_a),
    //     .probe6(adc_cs_n),
    //     .probe7(adc_rd_n),
    //     .probe8(adc_reset),
    //     .probe9(ch_idx),
    //     .probe10(adc_db_synced),
    //     .probe11(adc_db_synced2)
    // );
    always @(posedge clk) begin
        adc_db_synced  <= adc_db;
        adc_db_synced2 <= adc_db_synced;
    end

    // ============================================================
    // 主状态机
    // ============================================================

    always @(posedge clk) begin
        if (!rst_n) begin
            state            <= S_RESET;
            ch_idx           <= 4'd0;
            delay_cnt        <= 32'd0;
            ch1_tmp          <= 16'sd0;
            ch2_tmp          <= 16'sd0;
            ch3_tmp          <= 16'sd0;
            ch4_tmp          <= 16'sd0;
            ch1_buf          <= 16'sd0;
            ch2_buf          <= 16'sd0;
            ch3_buf          <= 16'sd0;
            ch4_buf          <= 16'sd0;
            ch1_data         <= 16'sd0;
            ch2_data         <= 16'sd0;
            ch3_data         <= 16'sd0;
            ch4_data         <= 16'sd0;
            frame_ready      <= 1'b0;
            sampling_started <= 1'b0;
            sample_overrun   <= 1'b0;
            sample_underrun  <= 1'b0;
            overrun_o        <= 1'b0;
            underrun_o       <= 1'b0;
            data_valid       <= 1'b0;
            adc_convst_a     <= 1'b0;
            adc_convst_b     <= 1'b0;
            adc_cs_n         <= 1'b1;
            adc_rd_n         <= 1'b1;
            adc_reset        <= 1'b1;
        end else begin

        data_valid  <= 1'b0;
        overrun_o   <= 1'b0;
        underrun_o  <= 1'b0;

        // ====================================================
        // 严格采样节拍处理
        // ====================================================
        // 1. data_valid 只在 sample_tick 上产生，因此上层看到的数据节拍严格等于 SAMPLE_RATE_HZ。
        // 2. sample_tick 到来时，如果上一帧已经读完，则输出上一帧。
        // 3. sample_tick 到来时，如果 ADC FSM 不是空闲状态，说明一个采样周期内没有完成转换和读数，锁存 overrun。
        // 4. sample_tick 到来时，如果上一帧还没准备好，说明输出断帧，锁存 underrun。

        if (sample_tick) begin
            if (frame_ready) begin
                ch1_data    <= ch1_buf;
                ch2_data    <= ch2_buf;
                ch3_data    <= ch3_buf;
                ch4_data    <= ch4_buf;
                data_valid  <= 1'b1;
                frame_ready <= 1'b0;
            end else if (sampling_started) begin
                underrun_o      <= 1'b1;
                sample_underrun <= 1'b1;
            end

            if (sampling_started && (state != S_IDLE)) begin
                overrun_o      <= 1'b1;
                sample_overrun <= 1'b1;
            end
        end

        case (state)

            // ====================================================
            // FPGA 配置完成后，自动给 AD7606/AD7606C 一个 RESET 高脉冲
            // ====================================================
            S_RESET: begin
                adc_convst_a <= 1'b0;
                adc_convst_b <= 1'b0;
                adc_cs_n     <= 1'b1;
                adc_rd_n     <= 1'b1;
                adc_reset    <= 1'b1;

                if (delay_cnt >= RESET_CLKS - 1) begin
                    delay_cnt <= 32'd0;
                    adc_reset <= 1'b0;
                    state     <= S_IDLE;
                end else begin
                    delay_cnt <= delay_cnt + 1'b1;
                end
            end

            // ====================================================
            // 空闲状态：只在严格 sample_tick 到来时启动 CONVST
            // ====================================================
            S_IDLE: begin
                adc_convst_a <= 1'b0;
                adc_convst_b <= 1'b0;
                adc_cs_n     <= 1'b1;
                adc_rd_n     <= 1'b1;
                adc_reset    <= 1'b0;

                if (sample_tick) begin
                    delay_cnt        <= 32'd0;
                    adc_convst_a     <= 1'b1;
                    adc_convst_b     <= 1'b1;
                    sampling_started <= 1'b1;
                    state            <= S_CONVST_HIGH;
                end
            end

            // ====================================================
            // CONVST A/B 保持高电平，满足最小脉宽要求
            // ====================================================
            S_CONVST_HIGH: begin
                adc_convst_a <= 1'b1;
                adc_convst_b <= 1'b1;
                adc_cs_n     <= 1'b1;
                adc_rd_n     <= 1'b1;

                if (delay_cnt >= CONVST_HIGH_CLKS - 1) begin
                    delay_cnt    <= 32'd0;
                    adc_convst_a <= 1'b0;
                    adc_convst_b <= 1'b0;
                    state        <= S_WAIT_BUSY_H;
                end else begin
                    delay_cnt <= delay_cnt + 1'b1;
                end
            end

            // ====================================================
            // 等待 BUSY 变高，确认 AD7606/AD7606C 已经开始转换
            // ====================================================
            S_WAIT_BUSY_H: begin
                adc_convst_a <= 1'b0;
                adc_convst_b <= 1'b0;
                adc_cs_n     <= 1'b1;
                adc_rd_n     <= 1'b1;

                if (busy_sync) begin
                    state <= S_WAIT_BUSY_L;
                end
            end

            // ====================================================
            // 等待 BUSY 变低，转换完成
            // ====================================================
            S_WAIT_BUSY_L: begin
                adc_cs_n <= 1'b1;
                adc_rd_n <= 1'b1;

                if (!busy_sync) begin
                    delay_cnt <= 32'd0;
                    state     <= S_READ_SETUP;
                end
            end

            // ====================================================
            // 读数据前，拉低 CS
            // ====================================================
            S_READ_SETUP: begin
                adc_cs_n <= 1'b0;
                adc_rd_n <= 1'b1;
                ch_idx   <= 4'd0;

                // 多等一个 clk，给总线一点建立时间
                if (delay_cnt >= 1) begin
                    delay_cnt <= 32'd0;
                    state     <= S_RD_LOW;
                end else begin
                    delay_cnt <= delay_cnt + 1'b1;
                end
            end

            // ====================================================
            // RD 拉低，AD7606/AD7606C 将当前通道数据放到 DB[15:0]
            // ====================================================
            S_RD_LOW: begin
                adc_cs_n <= 1'b0;
                adc_rd_n <= 1'b0;

                if (delay_cnt >= RD_LOW_CLKS - 1) begin
                    delay_cnt <= 32'd0;
                    state     <= S_RD_SAMPLE;
                end else begin
                    delay_cnt <= delay_cnt + 1'b1;
                end
            end

            // ====================================================
            // 采样 DB[15:0] (经 adc_db_synced2 两级寄存器同步)
            // 第 1 次读出 V1，第 2 次读出 V2，依次类推。
            // 这里不直接更新 chx_data，而是先写入 chx_tmp。
            // 使用第二级寄存器确保数据在 RD 低电平末尾充分稳定。
            // ====================================================
            S_RD_SAMPLE: begin
                adc_cs_n <= 1'b0;
                adc_rd_n <= 1'b0;

                case (ch_idx)
                    4'd0: ch1_tmp <= adc_db_synced2;
                    4'd1: ch2_tmp <= adc_db_synced2;
                    4'd2: ch3_tmp <= adc_db_synced2;
                    4'd3: ch4_tmp <= adc_db_synced2;
                    default: begin
                    end
                endcase

                delay_cnt <= 32'd0;
                state     <= S_RD_HIGH;
            end

            // ====================================================
            // RD 拉高，准备读下一个通道
            // ====================================================
            S_RD_HIGH: begin
                adc_cs_n <= 1'b0;
                adc_rd_n <= 1'b1;

                if (delay_cnt >= RD_HIGH_CLKS - 1) begin
                    delay_cnt <= 32'd0;

                    if (ch_idx >= ADC_TOTAL_CH - 1) begin
                        state <= S_DONE;
                    end else begin
                        ch_idx <= ch_idx + 1'b1;
                        state  <= S_RD_LOW;
                    end
                end else begin
                    delay_cnt <= delay_cnt + 1'b1;
                end
            end

            // ====================================================
            // 一帧采样读数完成
            // 注意：这里不拉高 data_valid。
            // 这里只把当前帧写入 chx_buf，并置 frame_ready。
            // 真正的 chx_data/data_valid 输出统一等到下一个 sample_tick。
            // ====================================================
            S_DONE: begin
                adc_cs_n <= 1'b1;
                adc_rd_n <= 1'b1;

                ch1_buf     <= ch1_tmp;
                ch2_buf     <= ch2_tmp;
                ch3_buf     <= ch3_tmp;
                ch4_buf     <= ch4_tmp;
                frame_ready <= 1'b1;

                state <= S_IDLE;
            end

            default: begin
                state <= S_IDLE;
            end

        endcase
        end
    end

endmodule
