# set_property IOSTANDARD LVCMOS33 [get_ports clk]
# set_property PACKAGE_PIN U18 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_os[0]}]
set_property PACKAGE_PIN H16 [get_ports {adc_os[0]}]
set_property PACKAGE_PIN H15 [get_ports {adc_os[1]}]
set_property PACKAGE_PIN H17 [get_ports {adc_os[2]}]
set_property PACKAGE_PIN G15 [get_ports adc_convst_b]
set_property PACKAGE_PIN E17 [get_ports adc_reset]
set_property IOSTANDARD LVCMOS33 [get_ports adc_reset]
set_property IOSTANDARD LVCMOS33 [get_ports adc_convst_b]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_os[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_os[2]}]
set_property PACKAGE_PIN N15 [get_ports adc_rd_n]
set_property PACKAGE_PIN D18 [get_ports adc_cs_n]
set_property IOSTANDARD LVCMOS33 [get_ports adc_convst_a]
set_property IOSTANDARD LVCMOS33 [get_ports adc_cs_n]
set_property IOSTANDARD LVCMOS33 [get_ports adc_rd_n]
set_property PACKAGE_PIN N16 [get_ports adc_busy]
set_property IOSTANDARD LVCMOS33 [get_ports adc_busy]
# set_property PACKAGE_PIN G17 [get_ports adc_frstdata]
# set_property IOSTANDARD LVCMOS33 [get_ports adc_frstdata]
set_property PACKAGE_PIN M14 [get_ports adc_convst_a]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_db[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_db[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_db[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_db[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_db[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_db[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_db[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_db[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_db[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_db[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_db[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_db[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_db[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_db[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_db[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_db[13]}]
set_property PACKAGE_PIN M15 [get_ports {adc_db[0]}]
set_property PACKAGE_PIN G18 [get_ports {adc_db[1]}]
set_property PACKAGE_PIN L14 [get_ports {adc_db[2]}]
set_property PACKAGE_PIN K17 [get_ports {adc_db[3]}]
set_property PACKAGE_PIN L15 [get_ports {adc_db[4]}]
set_property PACKAGE_PIN K18 [get_ports {adc_db[5]}]
set_property PACKAGE_PIN L16 [get_ports {adc_db[6]}]
set_property PACKAGE_PIN K14 [get_ports {adc_db[7]}]
set_property PACKAGE_PIN L17 [get_ports {adc_db[8]}]
set_property PACKAGE_PIN J14 [get_ports {adc_db[9]}]
set_property PACKAGE_PIN M17 [get_ports {adc_db[10]}]
set_property PACKAGE_PIN F16 [get_ports {adc_db[11]}]
set_property PACKAGE_PIN M18 [get_ports {adc_db[12]}]
set_property PACKAGE_PIN F17 [get_ports {adc_db[13]}]
set_property PACKAGE_PIN K16 [get_ports {adc_db[14]}]
set_property PACKAGE_PIN E18 [get_ports {adc_db[15]}]
# create_clock -period 20.000 -waveform {0.000 10.000} [get_ports clk]
